// Generated by scripts/gen-api-routes.mjs from src/server/http/routeTable.js. Do not edit.
import { handlersFor } from '../../../../../../src/server/http/routeTable.js';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const h = handlersFor('/farms/:id/sales/:recordId');
export const GET = h.GET;
export const POST = h.POST;
export const PUT = h.PUT;
export const PATCH = h.PATCH;
export const DELETE = h.DELETE;
export const OPTIONS = h.OPTIONS;
