import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowDownRight, ArrowUpRight, BrainCircuit, ChevronDown, ChevronUp, CloudLightning, Flag, Leaf, ShieldAlert, ShieldCheck, Sprout, Thermometer, Waves } from 'lucide-react';
import { useI18n } from '../../i18n/I18nProvider.jsx';
import { Badge, Card, Notice, ProgressBar, RiskBadge, SourceBadge, cx } from '../ui/index.jsx';
import { riskStyle } from '../../utils/risk.js';
import { dateTime, pct } from '../../utils/format.js';

export const RISK_ICON = { HEAT_ICE_ICE: Thermometer, STORM_LINE_DAMAGE: CloudLightning, POOR_GROWTH: Sprout, HARVEST_WINDOW: Leaf };

/** Structured factors from the backend (never generated by an LLM). */
export function FactorList({ factors = [], limit, showDecreasing = true }) {
  const { t, tx } = useI18n();
  const list = (showDecreasing ? factors : factors.filter((f) => f.direction === 'INCREASES')).slice(0, limit || factors.length);
  if (!list.length) return null;
  const max = Math.max(...list.map((f) => Math.abs(f.contribution)), 0.01);
  return (
    <ul className="space-y-2">
      {list.map((f) => {
        const up = f.direction === 'INCREASES';
        const Icon = up ? ArrowUpRight : ArrowDownRight;
        return (
          <li key={f.code} className="flex items-start gap-2 text-sm">
            <Icon className={cx('mt-0.5 h-4 w-4 shrink-0', up ? 'text-orange-600' : 'text-seaweed-600')} aria-label={up ? t('risk.increases') : t('risk.decreases')} />
            <div className="min-w-0 flex-1">
              <p className="text-slate-800">{tx(f, 'label')}</p>
              <div className="mt-1 flex items-center gap-2">
                <div className="h-1.5 w-24 overflow-hidden rounded-full bg-slate-100">
                  <div className={cx('h-full rounded-full', up ? 'bg-orange-500' : 'bg-seaweed-500')} style={{ width: `${(Math.abs(f.contribution) / max) * 100}%` }} />
                </div>
                {f.value && <span className="text-xs text-slate-500">{f.value}</span>}
              </div>
            </div>
          </li>
        );
      })}
    </ul>
  );
}

/** One risk type: level, probability, confidence, horizon, explanation and factors. */
export function RiskCard({ prediction, compact = false, defaultOpen = false }) {
  const { t, tx, lang } = useI18n();
  const [open, setOpen] = useState(defaultOpen);
  if (!prediction) return null;
  const Icon = RISK_ICON[prediction.riskType] || ShieldAlert;
  const style = riskStyle(prediction.riskLevel);
  return (
    <Card className={cx('border-l-4', style.border)}>
      <div className="p-4">
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-2">
            <Icon className={cx('h-5 w-5', style.text)} aria-hidden />
            <h3 className="font-semibold text-slate-900">{t(`risk.type.${prediction.riskType}`)}</h3>
          </div>
          <RiskBadge level={prediction.riskLevel} />
        </div>
        <div className="mt-3 flex items-end justify-between gap-3">
          <p className={cx('text-3xl font-bold', style.text)}>{pct(prediction.probability)}</p>
          <div className="text-right text-xs text-slate-500">
            <p>{t('risk.confidence')}: <span className="font-semibold text-slate-700">{pct(prediction.confidence)}</span></p>
            <p>{t('risk.horizon', { hours: prediction.forecastHorizonHours })}</p>
          </div>
        </div>
        <ProgressBar value={prediction.probability} level={prediction.riskLevel} className="mt-2" />
        {prediction.insufficientData && <Notice tone="warning" className="mt-3">{t('risk.insufficient')}</Notice>}
        {prediction.flagged && <Badge className="mt-2 bg-amber-50 text-amber-800 ring-amber-300"><Flag className="h-3 w-3" />{t('risk.flagged')}</Badge>}
        {!compact && (
          <>
            <button type="button" onClick={() => setOpen((o) => !o)} className="mt-3 flex items-center gap-1 text-sm font-semibold text-ocean-700 hover:text-ocean-900" aria-expanded={open}>
              {t('risk.why')} {open ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
            </button>
            {open && (
              <div className="mt-2 space-y-3">
                <p className="text-sm text-slate-600">{tx(prediction, 'explanation')}</p>
                <FactorList factors={prediction.factors} />
                <div className="flex flex-wrap items-center gap-2 border-t border-slate-100 pt-2 text-xs text-slate-500">
                  <SourceBadge source={prediction.dataSource} />
                  <ModelStatusBadge modelType={prediction.modelType} version={prediction.modelVersion} />
                  <span>{dateTime(prediction.createdAt, lang)}</span>
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </Card>
  );
}

export function ModelStatusBadge({ modelType, version, label }) {
  const { t } = useI18n();
  const text = label || (modelType === 'HYBRID' ? `${t('source.modelPrediction')}: ${version}` : t('risk.ruleBaseline'));
  return <Badge className="bg-slate-50 text-slate-700 ring-slate-200" title={version}><BrainCircuit className="h-3 w-3" aria-hidden />{text}</Badge>;
}

/** "HATUA INAYOFUATA" — the single most important approved action, with reasons. */
export function NextActionCard({ nextAction, insufficientDataMessage, farmId, onRecordAction, actionLoading }) {
  const { t, tx, lang } = useI18n();
  if (!nextAction) {
    return (
      <Card className="border-l-4 border-slate-300 p-4">
        <p className="text-xs font-bold uppercase tracking-wider text-slate-500">{t('risk.nextAction')}</p>
        <p className="mt-1 text-slate-700">{insufficientDataMessage ? insufficientDataMessage[lang] : t('common.noData')}</p>
        {farmId && <Link to="/farmer/observations" className="mt-2 inline-block text-sm font-semibold text-ocean-700">{t('actions.recordObservation')} →</Link>}
      </Card>
    );
  }
  const item = nextAction.recommendation.actionItem;
  const style = riskStyle(nextAction.riskLevel);
  return (
    <Card className={cx('overflow-hidden border-2', style.border)}>
      <div className={cx('flex items-center justify-between gap-2 px-4 py-2', style.badge)}>
        <p className="text-xs font-bold uppercase tracking-wider">{t('risk.nextAction')}</p>
        <span className="text-xs font-semibold">{t(`urgency.${item.urgency}`)} · {t(`risk.type.${nextAction.riskType}`)}</span>
      </div>
      <div className="space-y-3 p-4">
        <p className="text-lg font-semibold leading-snug text-slate-900">{tx(item, 'action')}</p>
        <p className="text-sm text-slate-600">{tx(item, 'explanation')}</p>
        {nextAction.reasons?.length > 0 && (
          <div>
            <p className="text-sm font-semibold text-slate-700">{t('risk.why')}</p>
            <ul className="mt-1 list-disc space-y-0.5 pl-5 text-sm text-slate-600">
              {nextAction.reasons.map((r) => <li key={r.code}>{tx(r, 'label')}</li>)}
            </ul>
          </div>
        )}
        <div className="flex flex-wrap items-center gap-2">
          {item.validated
            ? <Badge className="bg-seaweed-50 text-seaweed-700 ring-seaweed-500/30"><ShieldCheck className="h-3 w-3" />{t('common.validated')}</Badge>
            : <Badge className="bg-amber-50 text-amber-800 ring-amber-300" title={item.source}><ShieldAlert className="h-3 w-3" />{t('common.pendingValidation')}</Badge>}
          {item.escalateToExtension && <Badge className="bg-red-50 text-red-800 ring-red-300">{t('actions.contactExtension')}</Badge>}
        </div>
        {onRecordAction && nextAction.recommendation.status !== 'COMPLETED' && (
          <div className="flex flex-wrap gap-2 pt-1">
            <button type="button" disabled={actionLoading} onClick={() => onRecordAction(nextAction.recommendation, true)} className="rounded-lg bg-seaweed-600 px-4 py-2 text-sm font-semibold text-white hover:bg-seaweed-700 disabled:opacity-60">
              {t('actions.didIt')}
            </button>
            <button type="button" disabled={actionLoading} onClick={() => onRecordAction(nextAction.recommendation, false)} className="rounded-lg px-4 py-2 text-sm font-semibold text-slate-600 ring-1 ring-slate-300 hover:bg-slate-50 disabled:opacity-60">
              {t('actions.couldNot')}
            </button>
          </div>
        )}
        {nextAction.recommendation.status === 'COMPLETED' && <Notice tone="success">{t('risk.actionRecorded')}</Notice>}
      </div>
    </Card>
  );
}

export function EnvironmentSummary({ env, compact = false }) {
  const { t, lang } = useI18n();
  if (!env) return null;
  const items = [
    { k: 'sst', icon: Thermometer, label: t('env.seaTemp'), value: env.seaSurfaceTempC != null ? `${env.seaSurfaceTempC.toFixed(1)}°C` : '—', sub: env.sstAnomalyC != null ? t('env.vsNormal', { value: `${env.sstAnomalyC >= 0 ? '+' : ''}${env.sstAnomalyC.toFixed(1)}°C` }) : null, warn: env.sstAnomalyC > 0.5 },
    { k: 'wave', icon: Waves, label: t('env.waves'), value: env.waveHeightM != null ? `${env.waveHeightM.toFixed(1)} m` : '—', warn: env.waveHeightM > 1.5 },
    { k: 'wind', icon: CloudLightning, label: t('env.wind'), value: env.windSpeedKmh != null ? `${Math.round(env.windSpeedKmh)} km/h` : '—', warn: env.windSpeedKmh > 30 },
    { k: 'rain', icon: CloudLightning, label: t('env.rain'), value: env.rainfallMm != null ? `${env.rainfallMm.toFixed(1)} mm` : '—', warn: env.rainfallMm > 10 },
  ];
  return (
    <div>
      <div className={cx('grid gap-2', compact ? 'grid-cols-2' : 'grid-cols-2 sm:grid-cols-4')}>
        {items.map(({ k, icon: Icon, label, value, sub, warn }) => (
          <div key={k} className={cx('rounded-lg border p-2.5', warn ? 'border-orange-200 bg-orange-50' : 'border-slate-200 bg-slate-50')}>
            <p className="flex items-center gap-1 text-xs text-slate-500"><Icon className="h-3.5 w-3.5" aria-hidden />{label}</p>
            <p className="text-lg font-bold text-slate-900">{value}</p>
            {sub && <p className={cx('text-xs', warn ? 'font-semibold text-orange-700' : 'text-slate-500')}>{sub}</p>}
          </div>
        ))}
      </div>
      <div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-slate-500">
        <SourceBadge source={env.source} />
        {env.sstAnomalyDays > 0 && <span>{t('env.elevatedDays', { n: env.sstAnomalyDays })}</span>}
        {env.observedAt && <span>{t('common.lastUpdated', { time: dateTime(env.observedAt, lang) })}</span>}
      </div>
    </div>
  );
}
