/**
 * OpenAPI 3 description served at /api/docs (Swagger UI) and /api/docs.json.
 * Kept as a compact route table; request/response details are in docs/API.md.
 */
const R = (method, path, tag, summary, roles = 'any authenticated user', body = null) => ({ method, path, tag, summary, roles, body });

const routes = [
  R('get', '/health', 'System', 'Health check (database, demo mode, providers)', 'public'),
  R('get', '/species', 'System', 'Seaweed species list', 'public'),
  R('get', '/cooperatives/public', 'System', 'Cooperative codes for registration', 'public'),
  R('post', '/auth/register', 'Auth', 'Register a farmer or buyer (phone required, consent required)', 'public', { fullName: 'Asha Juma', phone: '0777 123 456', password: 'Passw0rd!', preferredLanguage: 'sw', role: 'FARMER', cooperativeCode: 'PAJE', consent: true }),
  R('post', '/auth/login', 'Auth', 'Login with phone (any Tanzanian format) or email, returns JWT', 'public', { identifier: '0777 000 001', password: '<demo password>' }),
  R('get', '/auth/me', 'Auth', 'Current user'),
  R('patch', '/auth/me', 'Auth', 'Update profile, language and SMS preferences'),
  R('post', '/auth/change-password', 'Auth', 'Change password (current password required)', 'any authenticated user', { currentPassword: '…', newPassword: '…' }),
  R('post', '/auth/logout', 'Auth', 'Logout (client discards token; audited)'),
  R('get', '/farms', 'Farms', 'List farms in scope (own / cooperative / all)', 'FARMER, COOPERATIVE_ADMIN, EXTENSION_OFFICER, ADMIN'),
  R('post', '/farms', 'Farms', 'Create farm (+ optional first planting cycle)', 'FARMER, EXTENSION_OFFICER, ADMIN'),
  R('get', '/farms/{id}', 'Farms', 'Farm detail with crop age, cycle, latest risks, forecast'),
  R('patch', '/farms/{id}', 'Farms', 'Update farm'),
  R('get', '/farms/{id}/cycles', 'Farms', 'Planting cycles'),
  R('post', '/farms/{id}/cycles', 'Farms', 'Record planting (start cycle)'),
  R('get', '/farms/{id}/observations', 'Records', 'Observations'),
  R('post', '/farms/{id}/observations', 'Records', 'Submit observation → risk engine re-runs', 'FARMER (owner), EXTENSION_OFFICER, ADMIN', { cropCondition: 'FAIR', whitening: true, breakage: false, epiphytes: false, percentAffected: 15 }),
  R('get', '/farms/{id}/harvests', 'Records', 'Harvest records'),
  R('post', '/farms/{id}/harvests', 'Records', 'Record harvest (difference + loss % computed)', 'owner', { harvestDate: '2026-09-20', actualQuantity: 150, unit: 'KG_DRY', qualityGrade: 'A', dryingMethod: 'RACK', pricePerKg: 1000 }),
  R('get', '/farms/{id}/losses', 'Records', 'Loss records'),
  R('post', '/farms/{id}/losses', 'Records', 'Record loss'),
  R('get', '/farms/{id}/risks', 'AI', 'Latest risk per type with factors + recommendation'),
  R('post', '/farms/{id}/risks/run', 'AI', 'Recalculate risk now'),
  R('get', '/farms/{id}/risks/history', 'AI', 'Risk history for charts'),
  R('get', '/farms/{id}/recommendations', 'AI', 'Recommendations for farm'),
  R('patch', '/farms/{id}/recommendations/{recId}', 'AI', 'Acknowledge / complete / dismiss recommendation'),
  R('get', '/farms/{id}/actions', 'Feedback loop', 'Farmer actions'),
  R('post', '/farms/{id}/actions', 'Feedback loop', 'Record action taken (links recommendation)', 'owner', { recommendationId: '<uuid>', actionTaken: true }),
  R('get', '/farms/{id}/outcomes', 'Feedback loop', 'Outcomes'),
  R('post', '/farms/{id}/outcomes', 'Feedback loop', 'Record outcome → model feedback label', 'owner', { recommendationId: '<uuid>', outcomeType: 'MINOR_LOSS', lossPercent: 5 }),
  R('get', '/farms/{id}/history', 'Records', 'Unified farm timeline'),
  R('get', '/farms/{id}/environment', 'Environment', 'Current + history for a farm'),
  R('get', '/farms/{id}/alerts', 'Alerts', 'Farm alerts'),
  R('get', '/farms/{id}/notes', 'Extension', 'Extension notes'),
  R('post', '/farms/{id}/notes', 'Extension', 'Add note / visit priority', 'EXTENSION_OFFICER, COOPERATIVE_ADMIN, ADMIN'),
  R('get', '/environment/current', 'Environment', 'Current environment (?farmId) with LIVE/CACHED/DEMO source'),
  R('get', '/environment/history', 'Environment', 'Environment history (?farmId&days)'),
  R('get', '/environment/providers', 'Environment', 'Provider status'),
  R('post', '/risk/predict', 'AI', 'Run AI for a farm; with overrides = simulation', 'FARMER, COOPERATIVE_ADMIN, EXTENSION_OFFICER, ADMIN', { farmId: '<uuid>', overrides: { sstAnomalyC: 1.6, waveHeightM: 0.4, windSpeedKmh: 12, rainfallMm: 0 } }),
  R('get', '/risk/{farmId}', 'AI', 'Latest risk for farm'),
  R('post', '/risk/predictions/{id}/flag', 'AI', 'Flag prediction / give feedback', 'EXTENSION_OFFICER, ADMIN'),
  R('get', '/actions', 'Action library', 'List action library'),
  R('get', '/actions/{id}', 'Action library', 'Get action'),
  R('post', '/actions', 'Action library', 'Create action (unvalidated)', 'ADMIN'),
  R('patch', '/actions/{id}', 'Action library', 'Update action (resets validation if text changes)', 'ADMIN'),
  R('post', '/actions/{id}/validate', 'Action library', 'Validate / unvalidate action', 'EXTENSION_OFFICER, ADMIN'),
  R('get', '/alerts', 'Alerts', 'Alerts in scope'),
  R('patch', '/alerts/{id}', 'Alerts', 'Acknowledge / resolve alert'),
  R('get', '/notifications', 'Alerts', 'My in-app notifications'),
  R('patch', '/notifications/{id}/read', 'Alerts', 'Mark read'),
  R('post', '/notifications/read-all', 'Alerts', 'Mark all read'),
  R('get', '/cooperatives', 'Cooperatives', 'Cooperatives in scope'),
  R('post', '/cooperatives', 'Cooperatives', 'Create cooperative', 'ADMIN'),
  R('get', '/cooperatives/mine/dashboard', 'Cooperatives', 'Dashboard for my cooperative', 'COOPERATIVE_ADMIN'),
  R('get', '/cooperatives/{id}/dashboard', 'Cooperatives', 'Cooperative dashboard', 'COOPERATIVE_ADMIN (own), EXTENSION_OFFICER, ADMIN'),
  R('get', '/cooperatives/{id}/farmers', 'Cooperatives', 'Cooperative farmers'),
  R('get', '/extension/dashboard', 'Extension', 'Extension dashboard', 'EXTENSION_OFFICER, ADMIN'),
  R('get', '/extension/observations', 'Extension', 'Observations for review'),
  R('patch', '/extension/observations/{id}/review', 'Extension', 'Review observation'),
  R('get', '/extension/recommendations', 'Extension', 'Recommendations for review'),
  R('patch', '/extension/recommendations/{id}/review', 'Extension', 'Review recommendation'),
  R('get', '/buyers', 'Buyers', 'Buyer list (for harvest records)'),
  R('get', '/buyers/forecast', 'Buyers', 'Anonymised supply forecast (7/14/30 days)', 'BUYER, COOPERATIVE_ADMIN, ADMIN'),
  R('post', '/buyers/demand', 'Buyers', 'Post demand', 'BUYER'),
  R('get', '/forecasts/harvest', 'Forecasts', 'Harvest forecasts in scope + aggregates'),
  R('post', '/forecasts/harvest/generate', 'Forecasts', 'Regenerate forecasts', 'COOPERATIVE_ADMIN, ADMIN'),
  R('post', '/ai/chat', 'AI', 'Farmer assistant (grounded in farm records)', 'any', { message: 'Kwa nini hatari yangu iko juu?', language: 'sw' }),
  R('get', '/ai/status', 'AI', 'Model + LLM status'),
  R('post', '/integrations/africastalking/ussd', 'Africa\'s Talking', 'USSD callback (form: sessionId, serviceCode, phoneNumber, networkCode, text) → CON/END text; requires ?secret=', 'Africa\'s Talking'),
  R('post', '/integrations/africastalking/sms', 'Africa\'s Talking', 'Incoming SMS callback (form: from, to, text, id, linkId); requires ?secret=', 'Africa\'s Talking'),
  R('post', '/integrations/africastalking/sms/delivery', 'Africa\'s Talking', 'SMS delivery report callback (form: id, status, failureReason); requires ?secret=', 'Africa\'s Talking'),
  R('post', '/uploads', 'Uploads', 'Upload observation photo (multipart field "image"; JPEG/PNG/WebP)'),
  R('get', '/uploads/{id}', 'Uploads', 'Download photo (authorised)'),
  R('get', '/admin/dashboard', 'Admin', 'System overview', 'ADMIN'),
  R('get', '/admin/users', 'Admin', 'Users', 'ADMIN'),
  R('post', '/admin/users', 'Admin', 'Create user', 'ADMIN'),
  R('patch', '/admin/users/{id}', 'Admin', 'Update user / roles', 'ADMIN'),
  R('get', '/admin/roles', 'Admin', 'Roles + permissions', 'ADMIN'),
  R('get', '/admin/settings', 'Admin', 'System settings (risk thresholds, AI mode, ...)', 'ADMIN'),
  R('put', '/admin/settings/{key}', 'Admin', 'Update a setting', 'ADMIN', { value: { MEDIUM: 0.3, HIGH: 0.6, CRITICAL: 0.8 } }),
  R('get', '/admin/models', 'Admin', 'ML models + metrics + field evaluation', 'ADMIN'),
  R('patch', '/admin/models/{id}', 'Admin', 'Activate / retire model', 'ADMIN'),
  R('get', '/admin/audit', 'Admin', 'Audit log', 'ADMIN'),
  R('get', '/admin/jobs', 'Admin', 'Scheduled jobs', 'ADMIN'),
  R('post', '/admin/jobs/{name}/run', 'Admin', 'Run job now', 'ADMIN'),
  R('get', '/admin/notification-logs', 'Admin', 'SMS/email delivery logs', 'ADMIN'),
  R('get', '/admin/integrations/africastalking', 'Admin', "Africa's Talking status (never shows the API key)", 'ADMIN'),
  R('post', '/admin/integrations/africastalking/test-sms', 'Admin', 'Send one real test SMS and return the provider result', 'ADMIN', { phone: '0777 000 001' }),
];

const paths = {};
for (const r of routes) {
  paths[r.path] ||= {};
  const params = [...r.path.matchAll(/\{(\w+)\}/g)].map((m) => ({ name: m[1], in: 'path', required: true, schema: { type: 'string' } }));
  paths[r.path][r.method] = {
    tags: [r.tag],
    summary: r.summary,
    description: `Access: ${r.roles}`,
    ...(r.roles === 'public' || r.roles === 'gateway' ? { security: [] } : {}),
    parameters: params,
    ...(r.body ? { requestBody: { content: { 'application/json': { example: r.body } } } } : {}),
    responses: {
      200: { description: 'Success — `{ success: true, data, message }`' },
      400: { description: 'VALIDATION_ERROR' },
      401: { description: 'UNAUTHORIZED' },
      403: { description: 'FORBIDDEN' },
      404: { description: 'NOT_FOUND' },
    },
  };
}

export const openApiSpec = {
  openapi: '3.0.3',
  info: {
    title: 'MwaniMlinzi AI API',
    version: '1.0.0',
    description: 'Zanzibar seaweed risk → action → outcome decision-support API. All errors use `{ success: false, error: { code, message, details } }`.',
  },
  servers: [{ url: '/api' }],
  components: { securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } } },
  security: [{ bearerAuth: [] }],
  paths,
};
